// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/gmail/authorize': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/gmail/authorize.get').default>>>>
    }
    '/api/auth/gmail/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/gmail/callback.get').default>>>>
    }
    '/api/bork/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/sales.get').default>>>>
    }
    '/api/bork/v2/credentials': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/credentials.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/credentials.post').default>>>>
    }
    '/api/bork/v2/cron': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/cron.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/cron.post').default>>>>
    }
    '/api/bork/v2/day-breakdown-v2': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/day-breakdown-v2.get').default>>>>
    }
    '/api/bork/v2/day-breakdown': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/day-breakdown.get').default>>>>
    }
    '/api/bork/v2/locations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/locations.get').default>>>>
    }
    '/api/bork/v2/run-scheduled': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/run-scheduled.get').default>>>>
    }
    '/api/bork/v2/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/sync.post').default>>>>
    }
    '/api/cron/data-integrity': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/data-integrity.get').default>>>>
    }
    '/api/daily-ops/insights': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/insights.get').default>>>>
    }
    '/api/daily-ops/locations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/locations.get').default>>>>
    }
    '/api/daily-ops/metrics/bundle': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/metrics/bundle.get').default>>>>
    }
    '/api/daily-ops/metrics/labor': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/metrics/labor.get').default>>>>
    }
    '/api/daily-ops/metrics/revenue-breakdown': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/metrics/revenue-breakdown.get').default>>>>
    }
    '/api/daily-ops/metrics/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/metrics/summary.get').default>>>>
    }
    '/api/daily-ops/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/overview.get').default>>>>
    }
    '/api/daily-ops/productivity': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/productivity.get').default>>>>
    }
    '/api/daily-ops/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/products.get').default>>>>
    }
    '/api/daily-ops/revenue': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/revenue.get').default>>>>
    }
    '/api/daily-ops/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/sales.get').default>>>>
    }
    '/api/daily-ops/workload': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/workload.get').default>>>>
    }
    '/api/data-integrity/run': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-integrity/run.get').default>>>>
    }
    '/api/data-sources/:datasource/field-mapping': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-sources/[datasource]/field-mapping.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-sources/[datasource]/field-mapping.post').default>>>>
    }
    '/api/data-sources/:datasource/raw-sample': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-sources/[datasource]/raw-sample.get').default>>>>
    }
    '/api/debug/bork-raw-sample': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug/bork-raw-sample.get').default>>>>
    }
    '/api/eitje/v2/credentials': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/credentials.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/credentials.post').default>>>>
    }
    '/api/eitje/v2/cron': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/cron.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/cron.post').default>>>>
    }
    '/api/eitje/v2/run-scheduled': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/run-scheduled.get').default>>>>
    }
    '/api/eitje/v2/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/sync.post').default>>>>
    }
    '/api/hours-aggregated': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hours-aggregated.get').default>>>>
    }
    '/api/hours-consistency-check': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hours-consistency-check.get').default>>>>
    }
    '/api/hours-row-detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hours-row-detail.get').default>>>>
    }
    '/api/hours-row-records': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hours-row-records.get').default>>>>
    }
    '/api/inbox/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/[id].get').default>>>>
    }
    '/api/inbox/bork/basis-report': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/bork/basis-report.get').default>>>>
    }
    '/api/inbox/bork/food-beverage': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/bork/food-beverage.get').default>>>>
    }
    '/api/inbox/bork/product-mix': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/bork/product-mix.get').default>>>>
    }
    '/api/inbox/bork/sales-per-hour': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/bork/sales-per-hour.get').default>>>>
    }
    '/api/inbox/bork/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/bork/sales.get').default>>>>
    }
    '/api/inbox/eitje/contracts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/eitje/contracts.get').default>>>>
    }
    '/api/inbox/eitje/finance': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/eitje/finance.get').default>>>>
    }
    '/api/inbox/eitje/hours': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/eitje/hours.get').default>>>>
    }
    '/api/inbox/gmail-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/gmail-status.get').default>>>>
    }
    '/api/inbox/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/list.get').default>>>>
    }
    '/api/inbox/manual-process-basis': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/manual-process-basis.get').default>>>>
    }
    '/api/inbox/parse': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/parse.post').default>>>>
    }
    '/api/inbox/power-bi/reports': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/power-bi/reports.get').default>>>>
    }
    '/api/inbox/process-all': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/process-all.post').default>>>>
    }
    '/api/inbox/process/:emailId': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/process/[emailId].post').default>>>>
    }
    '/api/inbox/sync-scheduled': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/sync-scheduled.get').default>>>>
    }
    '/api/inbox/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/sync.post').default>>>>
    }
    '/api/inbox/test-data/:type': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/test-data/[type].get').default>>>>
    }
    '/api/inbox/test-mapper': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/test-mapper.get').default>>>>
    }
    '/api/inbox/unprocessed-count': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/unprocessed-count.get').default>>>>
    }
    '/api/inbox/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/upload.post').default>>>>
    }
    '/api/inbox/watch': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/watch.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/watch.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/watch.post').default>>>>
    }
    '/api/inbox/watch/renew': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/watch/renew.get').default>>>>
    }
    '/api/inbox/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inbox/webhook.post').default>>>>
    }
    '/api/locations/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/locations/[id].delete').default>>>>
    }
    '/api/locations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/locations/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/locations/index.post').default>>>>
    }
    '/api/members/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].put').default>>>>
    }
    '/api/members/:id/connections': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id]/connections.get').default>>>>
    }
    '/api/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/index.post').default>>>>
    }
    '/api/menu/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/import.post').default>>>>
    }
    '/api/menu/items': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/items.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/items.get').default>>>>
    }
    '/api/menu/menus': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus.post').default>>>>
    }
    '/api/menu/menus/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id].patch').default>>>>
    }
    '/api/menu/menus/:id/export/excel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id]/export/excel.get').default>>>>
    }
    '/api/menu/menus/:id/products/bulk': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id]/products/bulk.post').default>>>>
    }
    '/api/menu/menus/:id/versions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id]/versions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id]/versions/index.post').default>>>>
    }
    '/api/menu/menus/copy': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/copy.post').default>>>>
    }
    '/api/notes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id].put').default>>>>
    }
    '/api/notes/:id/permanent': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id]/permanent.delete').default>>>>
    }
    '/api/notes/:id/restore': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id]/restore.post').default>>>>
    }
    '/api/notes/:id/share': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id]/share.post').default>>>>
    }
    '/api/notes/:id/todos/:todoId': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id]/todos/[todoId].put').default>>>>
    }
    '/api/notes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/index.post').default>>>>
    }
    '/api/sales-aggregated-products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales-aggregated-products.get').default>>>>
    }
    '/api/sales-aggregated-v2': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales-aggregated-v2.get').default>>>>
    }
    '/api/sales-aggregated': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales-aggregated.get').default>>>>
    }
    '/api/tags': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags/index.get').default>>>>
    }
    '/api/teams/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id].delete').default>>>>
    }
    '/api/teams': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/index.post').default>>>>
    }
    '/api/unified-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/unified-users/index.get').default>>>>
    }
    '/api/v3/aggregation/trigger': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v3/aggregation/trigger.post').default>>>>
    }
    '/api/v3/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v3/dashboard.get').default>>>>
    }
    '/api/v3/labor': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v3/labor.get').default>>>>
    }
    '/api/v3/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v3/sales.get').default>>>>
    }
    '/api/workers/active': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workers/active.get').default>>>>
    }
    '/api/workers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workers/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}