// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/bork/v2/credentials': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/credentials.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/credentials.post').default>>>>
    }
    '/api/bork/v2/cron': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/cron.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/cron.post').default>>>>
    }
    '/api/bork/v2/locations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/locations.get').default>>>>
    }
    '/api/bork/v2/run-scheduled': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/run-scheduled.get').default>>>>
    }
    '/api/bork/v2/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bork/v2/sync.post').default>>>>
    }
    '/api/cron/data-integrity': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/data-integrity.get').default>>>>
    }
    '/api/daily-ops/insights': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/insights.get').default>>>>
    }
    '/api/daily-ops/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/overview.get').default>>>>
    }
    '/api/daily-ops/productivity': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/productivity.get').default>>>>
    }
    '/api/daily-ops/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/products.get').default>>>>
    }
    '/api/daily-ops/revenue': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/revenue.get').default>>>>
    }
    '/api/daily-ops/sales': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/sales.get').default>>>>
    }
    '/api/daily-ops/workload': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/daily-ops/workload.get').default>>>>
    }
    '/api/data-integrity/run': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-integrity/run.get').default>>>>
    }
    '/api/data-sources/:datasource/field-mapping': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-sources/[datasource]/field-mapping.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-sources/[datasource]/field-mapping.post').default>>>>
    }
    '/api/data-sources/:datasource/raw-sample': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-sources/[datasource]/raw-sample.get').default>>>>
    }
    '/api/eitje/v2/credentials': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/credentials.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/credentials.post').default>>>>
    }
    '/api/eitje/v2/cron': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/cron.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/cron.post').default>>>>
    }
    '/api/eitje/v2/run-scheduled': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/run-scheduled.get').default>>>>
    }
    '/api/eitje/v2/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/eitje/v2/sync.post').default>>>>
    }
    '/api/hours-aggregated': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hours-aggregated.get').default>>>>
    }
    '/api/hours-consistency-check': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hours-consistency-check.get').default>>>>
    }
    '/api/hours-row-detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hours-row-detail.get').default>>>>
    }
    '/api/hours-row-records': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hours-row-records.get').default>>>>
    }
    '/api/locations/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/locations/[id].delete').default>>>>
    }
    '/api/locations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/locations/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/locations/index.post').default>>>>
    }
    '/api/members/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].put').default>>>>
    }
    '/api/members/:id/connections': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id]/connections.get').default>>>>
    }
    '/api/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/index.post').default>>>>
    }
    '/api/menu/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/import.post').default>>>>
    }
    '/api/menu/items': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/items.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/items.get').default>>>>
    }
    '/api/menu/menus': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus.post').default>>>>
    }
    '/api/menu/menus/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id].patch').default>>>>
    }
    '/api/menu/menus/:id/export/excel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id]/export/excel.get').default>>>>
    }
    '/api/menu/menus/:id/products/bulk': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id]/products/bulk.post').default>>>>
    }
    '/api/menu/menus/:id/versions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id]/versions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/[id]/versions/index.post').default>>>>
    }
    '/api/menu/menus/copy': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/menu/menus/copy.post').default>>>>
    }
    '/api/notes/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id].put').default>>>>
    }
    '/api/notes/:id/permanent': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id]/permanent.delete').default>>>>
    }
    '/api/notes/:id/restore': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id]/restore.post').default>>>>
    }
    '/api/notes/:id/share': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id]/share.post').default>>>>
    }
    '/api/notes/:id/todos/:todoId': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/[id]/todos/[todoId].put').default>>>>
    }
    '/api/notes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes/index.post').default>>>>
    }
    '/api/sales-aggregated': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales-aggregated.get').default>>>>
    }
    '/api/tags': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags/index.get').default>>>>
    }
    '/api/teams/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id].delete').default>>>>
    }
    '/api/teams': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/index.post').default>>>>
    }
    '/api/unified-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/unified-users/index.get').default>>>>
    }
    '/api/workers/active': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workers/active.get').default>>>>
    }
    '/api/workers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workers/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.2_@babel+core@7.29.0_db0@0.3.4_ioredis@5.10.1_magicast@0.5.2_nux_4ef35676041ca6aeac96e97cd57aa3e3/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.2_vite@7.3.1_jiti@2.6.1_lightningcss@1.32.0_terser@5.46.1_4abecf752c96ef90061202239c0fe9f1/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}